### ISSUE TITLE
Build/deploy action is triggered on PR

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/RBGreaterAgain#11]
This occurred in #10

**Comment by joschahenningsen** [comment]
Can [.github/workflows/branches.yml](../blob/master/.github/workflows/branches.yml) be deleted as long as we don't have tests @kordianbruck?

**Comment by kordianbruck** [comment]
Yea, for sure. It probably doesn't make a lot of sense to build the branch anyhow.
