### ISSUE TITLE
Cache data from RBG

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/RBGreaterAgain#4]
If I understand this correctly, live.rbg.tum.de is crawled every time the page is loaded. This would probably cause too much traffic from our server to the RBG, and might even get us banned. 

We should think about either
- Caching the html from RBG (pro: this could be done in ~5 lines of code) 
- Save streams and videos in a database and occasionally update it (pro: this reduces page loading times and server load because we only have to parse every stream once)

The second option would be more work but imo might be worth it. If you don't have the time for this feel free to assign me.

**Comment by kordianbruck** [comment]
Unless there is a use case for a DB (e.g. history, searching, filtering and paging), please don't. It makes deployment harder and is a failure point. I think using APCu here should be super sufficient.
